erDiagram

    Pais{
        int id PK
        str nombre
    }

    Plan {
        int id PK
        str nombre
        str descripcion
        float precio
        int cantidad_dispositivos
    }

    Calidad{
        int id PK
        str nombre
        str descripcion
    }

    Plan_calidad{
        int id PK
        int id_Plan FK
        int id_Calidad FK
    }
    
    Tipo_titulo{
        int id PK
        str nombre
        str descripcion
    }

    Titulo {
        int id PK
        str nombre_original
        str descripcion_original
        int id_Tipo_titulo FK
        int id_Pais FK
    }

    Elenco {
        int id PK
        str nombre
        str apellido
        date fecha_nacimiento
        str descripcion

    }

    Rol {
        int id PK
        str nombre
        str descripcion
    }

    Rol_elenco {
        int id PK
        int id_Rol FK
        int id_Elenco FK
    }
    
    Titulo_rol_elenco {
        int id PK
        int id_Rol_elenco FK
        int id_Titulo FK
    }

    Categoria {
        int id PK
        str nombre
        str descripcion
    }
    
    Titulo_categoria {
        int id PK
        int id_Titulo FK
        int id_Categoria FK
    }

    Idioma{
        int id PK
        str nombre
        str descripcion
    }

    Idioma_titulo{
        int id PK
        str nombre
        str descripcion
        int id_Idioma FK
        int id_Titulo FK
    }

    Contenido{
        int id PK
        str nombre
        str descripcion
        int seccion
        int orden 
        int id_Titulo FK
    }

    Imagen {
        int id PK
        int id_Titulo FK
        blob imagen
        str personaje

    }
    
    Tipo_perfil {
        int id PK
        str nombre
        int edad_maxima
    }

    Perfil {
        int id PK
        str nombre
        int id_Imagen FK
        int id_Tipo_perfil FK
    }

    Calificacion {
        int id PK
        str nombre
        float porcentaje_gusto
    }

    Perfil_titulo {
        int id PK
        int id_Perfil FK
        int id_Titulo FK
        int id_Calificacion FK
        bool por_ver
    }

    Perfil_contenido {
        int id PK
        int id_Perfil FK
        int id_Contenido FK
        int segundos_vistos
        date ultima_visualizacion
    }
    
    Idioma_contenido{
        int id PK
        int id_Idioma FK
        int id_Contenido FK
    }

    Calidad_idioma_contenido{
        int id PK
        int id_Idioma_contenido FK
        int id_Calidad FK
        blob archivo
    }

    Marca_tarjeta{
        int id PK
        str nombre
        int numero_asignado
        str descripcion
    }

    Metodo_pago {
        int id PK
        str nombre
        str descripcion
    }

    Tarjeta {
        int id PK
        str numero
        str nombre_titular
        date fecha_vencimiento
        int id_Marca_tarjeta FK
        int id_Metodo_pago FK
        bool habilitado
    }

    Usuario {
        int id PK
        str nombre
        str apellido
        str email
        str telefono 
        %%OPC Contiene caracteristica
        str clave 
        %%cifrado
        int id_Pais FK
        int id_Idioma FK
        int id_Tarjeta FK
    
    }

    Registro{
        int id PK
        int id_Usuario FK
        %%cada inicio de sesion genera un token unico que indica donde se ha iniciado sesion, este mismo se almacena en las cookies del navegador para luego poder acceder nuevamente sin necesidad de loguearse
        str token_dispositivo 
        %%indica si el token es valido aún
        str sistema_operativo
        date hora_conexion
        bool estado_sesion
    }

    Suscripcion {
        int id PK
        int id_Usuario FK
        int id_Plan FK
        date fecha_incripcion
        date fecha_cancelacion
        bool habilitado
    }

    Estado_cobro{
        int id PK
        str nombre
        str descripcion
    }

    Cobro{
        int id PK
        int num_factura
        int id_Suscripcion FK
        date fecha_cobro
        int id_Estado_cobro FK
        int id_Tarjeta FK 
        int numero_autorizacion
        %%id_tarjeta se saca de suscrpcion a la hora del cobro, y luego se almacena por historial
        float monto
    }

    Calidad ||--o{ Plan_calidad: ""
    Titulo ||--o{ Perfil_titulo: ""
    Calificacion ||--o{ Perfil_titulo:""
    Perfil ||--o{ Perfil_contenido:""
    Plan_calidad }o--||Plan: ""
    Titulo_rol_elenco }o--|| Titulo: ""
    Titulo_categoria }o--|| Titulo: "" 
    Tipo_titulo ||--o{ Titulo: ""
    Pais }o--|| Titulo: ""
    Titulo ||--o{ Imagen: ""
    Titulo ||--o{ Contenido: ""
    Contenido ||--o{ Perfil_contenido:""
    Perfil ||--o{ Perfil_titulo:""
    Contenido ||--o{ Idioma_contenido:""
    Elenco ||--o{ Rol_elenco: ""
    Rol ||--o{ Rol_elenco: ""
    Rol_elenco ||--o{ Titulo_rol_elenco: ""
    Categoria ||--o{ Titulo_categoria:""
    Tipo_perfil ||--o{ Perfil:""
    Imagen ||--o{ Perfil:""
    Idioma_contenido ||--o{ Calidad_idioma_contenido:""
    Calidad_idioma_contenido }o--|| Calidad: ""
    Idioma ||--o{ Idioma_contenido:""
    Titulo ||--o{ Idioma_titulo: ""
    Idioma_titulo }o--|| Idioma:""
    Registro }o--|| Usuario:""
    Pais ||--o{ Usuario: ""
    Plan ||--o{ Suscripcion: ""
    Usuario ||--o{ Suscripcion:""
    Suscripcion ||--o{ Cobro:""
    Estado_cobro ||--o{ Cobro:""
    Tarjeta ||--o{ Cobro:""
    Usuario }o--|| Tarjeta:""
    Marca_tarjeta ||--o{ Tarjeta:""
    Metodo_pago ||--o{ Tarjeta:""
