# Generated by Django 6.0.7 on 2026-08-30 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancalidad',
            name='calidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_calidades', to='streaming.calidad'),
        ),
        migrations.AddField(
            model_name='plancalidad',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_calidades', to='pagos.plan'),
        ),
        migrations.AddField(
            model_name='precio',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='pagos.plan'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='pagos.plan'),
        ),
    ]
