# Generated by Django 6.0.7 on 2026-08-30 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cobro',
            name='suscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='pagos.suscripcion'),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='marca_tarjeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarjetas', to='pagos.marcatarjeta'),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='metodo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarjetas', to='pagos.metodopago'),
        ),
        migrations.AddField(
            model_name='cobro',
            name='tarjeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='pagos.tarjeta'),
        ),
    ]
