# Generated by Django 6.0.7 on 2026-08-30 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streaming', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcontenido',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_contenidos', to='user.perfil'),
        ),
        migrations.AddField(
            model_name='perfiltitulo',
            name='calificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_titulos', to='streaming.calificacion'),
        ),
        migrations.AddField(
            model_name='perfiltitulo',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_titulos', to='user.perfil'),
        ),
        migrations.AddField(
            model_name='porver',
            name='perfil_titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='porver', to='streaming.perfiltitulo'),
        ),
        migrations.AddField(
            model_name='rolelenco',
            name='elenco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_elencos', to='streaming.elenco'),
        ),
        migrations.AddField(
            model_name='rolelenco',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_elencos', to='streaming.rol'),
        ),
        migrations.AddField(
            model_name='subtitulo',
            name='contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitulos', to='streaming.contenido'),
        ),
        migrations.AddField(
            model_name='subtitulo',
            name='idioma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subtitulos', to='streaming.idioma'),
        ),
        migrations.AddField(
            model_name='titulo',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titulos', to='streaming.pais'),
        ),
        migrations.AddField(
            model_name='titulo',
            name='tipo_titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titulos', to='streaming.tipotitulo'),
        ),
        migrations.AddField(
            model_name='perfiltitulo',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_titulos', to='streaming.titulo'),
        ),
        migrations.AddField(
            model_name='idiomatitulo',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idioma_titulos', to='streaming.titulo'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='streaming.titulo'),
        ),
        migrations.AddField(
            model_name='titulocategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulo_categorias', to='streaming.categoria'),
        ),
        migrations.AddField(
            model_name='titulocategoria',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulo_categorias', to='streaming.titulo'),
        ),
        migrations.AddField(
            model_name='titulorolelenco',
            name='rol_elenco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulo_rol_elencos', to='streaming.rolelenco'),
        ),
        migrations.AddField(
            model_name='titulorolelenco',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulo_rol_elencos', to='streaming.titulo'),
        ),
    ]
